Update project files to support uv workflows

diff --git a/.github/workflows/python-tests.yml b/.github/workflows/python-tests.yml
--- a/.github/workflows/python-tests.yml
+++ b/.github/workflows/python-tests.yml
@@ -1,14 +1,12 @@
 name: "python tests and coverage"
 # Uses:
-# https://github.com/actions/setup-python
-# https://github.com/actions/checkout
-# https://github.com/actions/download-artifact
-# https://github.com/actions/upload-artifact
+# https://github.com/actions/checkout : v4.2.2 11bd71901bbe5b1630ceea73d27597364c9af683
+# https://github.com/actions/download-artifact : v5.0.0 634f93cb2916e3fdff6788551b99b062d0335ce0
+# https://github.com/actions/upload-artifact : v4.6.2 ea165f8d65b6e75b540449e92b4886f43607fa02
+# https://github.com/astral-sh/setup-uv : v6.4.3 e92bafb6253dcd438e0484186d7669ea7a8ca1cc
 
 on:
   pull_request:
-    branches:
-      - "main"
   push:
     branches:
       - "main"
@@ -21,37 +19,33 @@ jobs:
       fail-fast: false
       matrix:
         os:
-          - "macos-latest"
+          # - "macos-latest"
           - "windows-latest"
           - "ubuntu-latest"
         python-version:
-          - "3.11"
           - "3.12"
 
     steps:
       - name: "Repo checkout"
-        uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11"
+        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
 
-      - name: "Set up Python ${{ matrix.python-version }}"
-        uses: "actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c"
+      - name: "Install the latest version of uv"
+        uses: "astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc"
         with:
+          version: "latest"
           python-version: "${{ matrix.python-version }}"
-          allow-prereleases: true
-
-      - name: "Install nox"
-        run: |
-          python -m pip install --upgrade pip nox
+          enable-cache: true
 
       - name: "Run tests and coverage via nox"
-        run: |
-          nox --session tests_with_coverage-${{ matrix.python-version }}
+        run: "uvx nox --session test -- partial-coverage"
 
       - name: "Save coverage artifact"
-        uses: "actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3"
+        uses: "actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02"
         with:
           name: "coverage-artifact-${{ matrix.os}}-${{ matrix.python-version}}"
           path: ".coverage.*"
           retention-days: 1
+          include-hidden-files: true
 
   coverage-compile:
     name: "coverage compile"
@@ -59,55 +53,53 @@ jobs:
     runs-on: "ubuntu-latest"
     steps:
       - name: "Repo checkout"
-        uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11"
+        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
 
-      - name: "Set up Python"
-        uses: "actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c"
+      - name: "Install the latest version of uv"
+        uses: "astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc"
         with:
-          python-version: "3.11"
-
-      - name: "Install nox"
-        run: |
-          python -m pip install --upgrade pip nox
+          version: "latest"
+          enable-cache: true
 
       - name: "Download coverage artifacts"
-        uses: "actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427"
+        uses: "actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0"
         with:
           pattern: "coverage-artifact-*"
           merge-multiple: true
 
-      - name: "Compile coverage data, print report"
+      - name: "Compile coverage data"
+        run: "uvx nox --session combine"
+
+      - name: "Post summary to step summary"
         run: |
-          nox --session coverage_combine_and_report
+          export COVERAGE_REQUIRED=$(<.required-coverage)
           export TOTAL=$(python -c "import json;print(json.load(open('coverage.json'))['totals']['percent_covered_display'])")
           echo "TOTAL=$TOTAL" >> $GITHUB_ENV
+          echo "### Minimum coverage required: ${COVERAGE_REQUIRED}%" >> $GITHUB_STEP_SUMMARY
           echo "### Total coverage: ${TOTAL}%" >> $GITHUB_STEP_SUMMARY
+          if [ ${COVERAGE_REQUIRED} -gt $TOTAL ]; then
+            exit 1
+          fi
 
-  mypy-check:
-    name: "mypy strict enforcement"
+  linters-and-formatters:
+    name: "linters and formatters"
     runs-on: "ubuntu-latest"
     steps:
       - name: "Repo checkout"
-        uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11"
+        uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
 
-      - name: "Set up Python"
-        uses: "actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c"
+      - name: "Install the latest version of uv"
+        uses: "astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc"
         with:
-          python-version: "3.11"
+          version: "latest"
+          enable-cache: true
 
-      - name: "Install nox"
-        run: |
-          python -m pip install --upgrade pip nox
+      - name: "Run linters and formatters"
+        run: "uvx nox --session format lint"
 
-      - name: "Enforce strict type annotations with mypy"
+      - name: "Check for any unstaged changes"
         run: |
-          nox --session mypy_check
-
-  ci-success:
-    name: "CI steps all completed successfully"
-    needs: ["coverage-compile", "mypy-check"]
-    runs-on: "ubuntu-latest"
-    steps:
-      - name: "Success"
-        run: |
-          echo "If you are seeing this, the CI run was successful."
+          if [ -n "$(git status --porcelain)" ]; then
+            echo "#### Format or Lint changes found. Please run 'uvx nox' locally and push the changes." >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
